### ISSUE TITLE
Need gpg secret key to unlock afplib

### ISSUE THREAD

**Issue by harrydaihaolin** [yan74/afplib#42]
Hi Yan74,

It seems that the project needs the secret key to unlock the lib. Can you provide the key?

```bash
gpg: no default secret key: secret key not available
gpg: signing failed: secret key not available
```
Thanks,
Haolin

**Comment by yan74** [comment]
Hi @harrydaihaolin,

I need to sign the jar packages in order to upload to maven central. You don't need to sign yourself for your personal use. Either do

`mvn package`

or

`mvn install -Dgpg.skip`

**Comment by harrydaihaolin** [comment]
Hi @yan74 ,

Thank you, issue fixed.

**Comment by harrydaihaolin** [comment]
Hi @yan74 ,
I'm able to install the package. However, when I tried to run the program, it seems to require the signature file, is it because of the gpg package that I skipped?
```Java
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:330)
        at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:263)
        at java.util.jar.JarVerifier.processEntry(JarVerifier.java:318)
        at java.util.jar.JarVerifier.update(JarVerifier.java:230)
        at java.util.jar.JarFile.initializeVerifier(JarFile.java:383)
        at java.util.jar.JarFile.getInputStream(JarFile.java:450)
        at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:987)
        at sun.misc.Resource.cachedInputStream(Resource.java:77)
        at sun.misc.Resource.getByteBuffer(Resource.java:160)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
```
Cheers,
Haolin

**Comment by yan74** [comment]
@harrydaihaolin 
I am not sure which program you are referring to. Can you past the complete command line?

**Comment by harrydaihaolin** [comment]
@yan74 I'm just trying to run the default hello world program. The only configuration I made is to put a build configuration for mainclass in pom.xml. So I firstly ran the `mvn package` in the `../afplib/` directory, then I `cd HelloWorld`, `mvn package again`, `cd target` `java -jar `, `java -jar .\HelloWorld-0.0.1-SNAPSHOT.jar` and it got me this error.

**Comment by yan74** [comment]
so this is what I tried (actually I am not sure if I ever tried to run the HelloWorld outside an IDE):

```sh
mvn clean install -Dskip.gpg
cd HelloWorld/
mvn clean package -Dskip.gpg
java -cp ../org.afplib/target/afplib-0.0.15-SNAPSHOT-jar-with-dependencies.jar:target/HelloWorld-0.0.1-SNAPSHOT.jar HelloWorld
```
I guess the error you are seeing is because of missing dependencies (like e.g. EMF).

**Comment by harrydaihaolin** [comment]
Thank you for the solution. I'm not able to repeat the steps but I decided to go for the IDE and it worked on Eclipse.
